/**
 * Per-state list of named water bodies the AI stocking extractor
 * should prioritize. Seeded with the same major fisheries the
 * frontend waterbody registry knows about — kept inline here so the
 * functions package doesn't have to import frontend code.
 *
 * The list isn't exhaustive (state DNRs stock hundreds of waters
 * each year) — it's the "if events exist on these, make sure to
 * surface them" hint. Claude is free to return events on other
 * waters too, as long as each event names a specific body.
 *
 * Add an entry when:
 *   - You expand the waterbody registry for that state
 *   - A user reports missing stocking data on a specific water
 */
export const FOCUS_WATERS: Record<string, string[]> = {
  MI: [
    // Salmon / steelhead rivers
    'Manistee River',
    'Big Manistee River',
    'Au Sable River',
    'Pere Marquette River',
    'Muskegon River',
    'White River',
    'Kalamazoo River',
    'St. Joseph River',
    'Grand River',
    'Boardman River',
    'Jordan River',
    'Bear River',
    'Pigeon River',
    'Thunder Bay River',
    'Rifle River',
    'Two Hearted River',
    'Fox River',
    'Tahquamenon River',
    'Sturgeon River',
    // Inland lakes (often stocked)
    'Higgins Lake',
    'Houghton Lake',
    'Torch Lake',
    'Crystal Lake',
    'Glen Lake',
    'Lake Charlevoix',
    'Walloon Lake',
    'Lake Leelanau',
    'Hubbard Lake',
    'Burt Lake',
    'Mullett Lake',
    'Black Lake',
    'Hamlin Lake',
    'Cadillac Lake',
    'Mitchell Lake',
    'Lake Margrethe',
    'Lake Gogebic',
    'Manistique Lake',
    'Indian Lake',
    'Brevoort Lake',
    // Great Lakes shoreline + bays
    'Lake Michigan',
    'Lake Huron',
    'Lake Superior',
    'Lake St. Clair',
    'Grand Traverse Bay',
    'Saginaw Bay',
    'Little Traverse Bay',
    'Thunder Bay',
    'Tawas Bay',
    'Whitefish Bay',
    'Keweenaw Bay',
  ],
  TN: [
    'Caney Fork River',
    'South Holston River',
    'Watauga River',
    'Clinch River',
    'Elk River',
    'Hiwassee River',
    'Tellico River',
    'Little River',
    'Holston River',
    'French Broad River',
    'Cumberland River',
    'Tennessee River',
    'Norris Lake',
    'Center Hill Lake',
    'Dale Hollow Lake',
    'Tims Ford Lake',
    'Cherokee Lake',
    'Douglas Lake',
    'Fort Loudoun Lake',
    'Tellico Lake',
    'Watts Bar Lake',
    'Chickamauga Lake',
    'Pickwick Lake',
    'Kentucky Lake',
    'Reelfoot Lake',
    'Percy Priest Lake',
    'Cordell Hull Lake',
    'Boone Lake',
  ],
  KY: [
    'Lake Cumberland',
    'Cumberland River',
    'Dale Hollow Lake',
    'Cave Run Lake',
    'Licking River',
    'Green River Lake',
    'Green River',
    'Laurel River Lake',
    'Laurel River',
    'Kentucky River',
    'Barren River Lake',
    'Nolin Lake',
  ],
  NC: [
    'Lake Norman',
    'Lake James',
    'Hiwassee Lake',
    'Nantahala River',
    'Davidson River',
    'South Toe River',
    'French Broad River',
    'Linville River',
    'Tuckasegee River',
  ],
  IN: ['Lake Wawasee', 'Patoka Lake', 'Monroe Lake', 'St. Joseph River'],
  GA: [
    // Mountain trout streams (the bulk of weekly stocking)
    'Chattahoochee River',
    'Toccoa River',
    'Soque River',
    'Chattooga River',
    'Coosawattee River',
    'Noontootla Creek',
    'Cooper Creek',
    'Rock Creek',
    'Amicalola Creek',
    'Dukes Creek',
    'Tallulah River',
    'Holly Creek',
    'Conasauga River',
    'Etowah River',
    // Reservoirs
    'Lake Lanier',
    'Lake Hartwell',
    'Lake Allatoona',
    'Carters Lake',
    'Lake Blue Ridge',
    'Lake Chatuge',
    'Lake Nottely',
    'Lake Burton',
    'Lake Russell',
    'Clarks Hill Lake',
    'Lake Thurmond',
    'Lake Oconee',
    'Lake Sinclair',
    'West Point Lake',
    // Larger rivers
    'Flint River',
    'Ocmulgee River',
    'Altamaha River',
    'Savannah River',
  ],
  FL: [
    'Lake Okeechobee',
    'St. Johns River',
    'Suwannee River',
    'Lake George',
    'Rodman Reservoir',
  ],
  AL: [
    'Lake Guntersville',
    'Wheeler Lake',
    'Lake Eufaula',
    'Lake Martin',
    'Smith Lake',
    'Tennessee River',
  ],
  AR: [
    'Bull Shoals Lake',
    'White River',
    'Norfork Lake',
    'Lake Ouachita',
    'Greers Ferry Lake',
    'Beaver Lake',
    'Little Red River',
  ],
  PA: [
    'Lake Erie',
    'Allegheny River',
    'Susquehanna River',
    'Delaware River',
    'Pine Creek',
    'Spring Creek',
    'Penns Creek',
    'Yellow Breeches Creek',
    'Letort Spring Run',
  ],
  IL: ['Lake Michigan', 'Mississippi River', 'Illinois River', 'Rend Lake'],
  MS: ['Ross Barnett Reservoir', 'Pickwick Lake', 'Pascagoula River'],
  OK: [
    'Lake Texoma',
    'Broken Bow Lake',
    'Lake Eufaula',
    'Skiatook Lake',
    'Tenkiller Lake',
    'Lower Mountain Fork River',
  ],
  MT: [
    'Madison River',
    'Bighorn River',
    'Missouri River',
    'Yellowstone River',
    'Flathead Lake',
    'Holter Lake',
    'Hauser Lake',
    'Canyon Ferry Lake',
  ],
  ID: [
    'Snake River',
    'Henrys Fork',
    'South Fork Snake',
    'Lake Pend Oreille',
    'Coeur d Alene Lake',
    'Salmon River',
  ],
  UT: [
    'Flaming Gorge Reservoir',
    'Strawberry Reservoir',
    'Provo River',
    'Green River',
    'Bear Lake',
  ],
  CO: [
    'Spinney Mountain Reservoir',
    'Eleven Mile Reservoir',
    'Blue Mesa Reservoir',
    'Antero Reservoir',
    'South Platte River',
    'Arkansas River',
    'Colorado River',
    'Gunnison River',
    'Yampa River',
  ],
};
