/**
 * Per-state list of named water bodies the AI stocking extractor
 * should prioritize. Seeded with the same major fisheries the
 * frontend waterbody registry knows about — kept inline here so the
 * functions package doesn't have to import frontend code.
 *
 * The list isn't exhaustive (state DNRs stock hundreds of waters
 * each year) — it's the "if events exist on these, make sure to
 * surface them" hint. Claude is free to return events on other
 * waters too, as long as each event names a specific body.
 *
 * Add an entry when:
 *   - You expand the waterbody registry for that state
 *   - A user reports missing stocking data on a specific water
 */
export const FOCUS_WATERS: Record<string, string[]> = {
  MI: [
    // Salmon / steelhead rivers
    'Manistee River',
    'Big Manistee River',
    'Au Sable River',
    'Pere Marquette River',
    'Muskegon River',
    'White River',
    'Kalamazoo River',
    'St. Joseph River',
    'Grand River',
    'Boardman River',
    'Jordan River',
    'Bear River',
    'Pigeon River',
    'Thunder Bay River',
    'Rifle River',
    'Two Hearted River',
    'Fox River',
    'Tahquamenon River',
    'Sturgeon River',
    // Inland lakes (often stocked)
    'Higgins Lake',
    'Houghton Lake',
    'Torch Lake',
    'Crystal Lake',
    'Glen Lake',
    'Lake Charlevoix',
    'Walloon Lake',
    'Lake Leelanau',
    'Hubbard Lake',
    'Burt Lake',
    'Mullett Lake',
    'Black Lake',
    'Hamlin Lake',
    'Cadillac Lake',
    'Mitchell Lake',
    'Lake Margrethe',
    'Lake Gogebic',
    'Manistique Lake',
    'Indian Lake',
    'Brevoort Lake',
    // Great Lakes shoreline + bays
    'Lake Michigan',
    'Lake Huron',
    'Lake Superior',
    'Lake St. Clair',
    'Grand Traverse Bay',
    'Saginaw Bay',
    'Little Traverse Bay',
    'Thunder Bay',
    'Tawas Bay',
    'Whitefish Bay',
    'Keweenaw Bay',
  ],
  TN: [
    'Caney Fork River',
    'South Holston River',
    'Watauga River',
    'Clinch River',
    'Elk River',
    'Hiwassee River',
    'Tellico River',
    'Little River',
    'Holston River',
    'French Broad River',
    'Cumberland River',
    'Tennessee River',
    'Norris Lake',
    'Center Hill Lake',
    'Dale Hollow Lake',
    'Tims Ford Lake',
    'Cherokee Lake',
    'Douglas Lake',
    'Fort Loudoun Lake',
    'Tellico Lake',
    'Watts Bar Lake',
    'Chickamauga Lake',
    'Pickwick Lake',
    'Kentucky Lake',
    'Reelfoot Lake',
    'Percy Priest Lake',
    'Cordell Hull Lake',
    'Boone Lake',
  ],
  KY: [
    'Lake Cumberland',
    'Cumberland River',
    'Dale Hollow Lake',
    'Cave Run Lake',
    'Licking River',
    'Green River Lake',
    'Green River',
    'Laurel River Lake',
    'Laurel River',
    'Kentucky River',
    'Barren River Lake',
    'Nolin Lake',
  ],
  NC: [
    'Lake Norman', 'Lake James', 'Lake Wylie', 'Lake Tillery', 'Jordan Lake',
    'Hiwassee Lake', 'Fontana Lake', 'Lake Santeetlah', 'Lake Jocassee',
    'Lake Glenville',
    'Nantahala River', 'Davidson River', 'South Toe River', 'Tuckasegee River',
    'French Broad River', 'Nolichucky River', 'Linville River', 'Watauga River',
    'Pigeon River',
  ],
  IN: [
    'Trail Creek', 'St. Joseph River', 'Lake Michigan',
    'Monroe Lake', 'Patoka Lake', 'Mississinewa Lake', 'Salamonie Lake',
    'Brookville Lake', 'Cecil M. Harden Lake', 'Lake Wawasee',
    'Lake Maxinkuckee', 'Tippecanoe River', 'Wabash River', 'Sugar Creek',
  ],
  GA: [
    // Mountain trout streams (the bulk of weekly stocking)
    'Chattahoochee River',
    'Toccoa River',
    'Soque River',
    'Chattooga River',
    'Coosawattee River',
    'Noontootla Creek',
    'Cooper Creek',
    'Rock Creek',
    'Amicalola Creek',
    'Dukes Creek',
    'Tallulah River',
    'Holly Creek',
    'Conasauga River',
    'Etowah River',
    // Reservoirs
    'Lake Lanier',
    'Lake Hartwell',
    'Lake Allatoona',
    'Carters Lake',
    'Lake Blue Ridge',
    'Lake Chatuge',
    'Lake Nottely',
    'Lake Burton',
    'Lake Russell',
    'Clarks Hill Lake',
    'Lake Thurmond',
    'Lake Oconee',
    'Lake Sinclair',
    'West Point Lake',
    // Larger rivers
    'Flint River',
    'Ocmulgee River',
    'Altamaha River',
    'Savannah River',
  ],
  FL: [
    'Lake Okeechobee', 'Lake Kissimmee', 'Lake Tohopekaliga', 'Lake George',
    'Lake Apopka', 'Rodman Reservoir', 'Stick Marsh', 'Lake Talquin',
    'Lake Seminole', 'Lake Tarpon',
    'St. Johns River', 'Suwannee River', 'Withlacoochee River',
    'Apalachicola River', 'Choctawhatchee River',
  ],
  AL: [
    'Lake Guntersville', 'Wheeler Lake', 'Wilson Lake', 'Pickwick Lake',
    'Lake Martin', 'Logan Martin Lake', 'Neely Henry Lake', 'Lake Weiss',
    'Lewis Smith Lake', 'Smith Lake', 'Lake Eufaula',
    'Tennessee River', 'Coosa River', 'Mobile Bay', 'Mobile-Tensaw Delta',
  ],
  AR: [
    'Bull Shoals Lake', 'White River', 'Norfork Lake', 'Greers Ferry Lake',
    'Lake Ouachita', 'Beaver Lake', 'Lake DeGray', 'Lake Maumelle',
    'Little Red River', 'Norfork Tailwater', 'Buffalo National River',
    'Kings River', 'Spring River',
  ],
  MS: [
    'Sardis Lake', 'Grenada Lake', 'Enid Lake', 'Arkabutla Lake',
    'Bay Springs Lake', 'Ross Barnett Reservoir', 'Pickwick Lake',
    'Pascagoula River', 'Yazoo River', 'Big Black River',
  ],
  OK: [
    'Lake Texoma', 'Eufaula Lake', 'Keystone Lake', 'Skiatook Lake',
    'Tenkiller Ferry Lake', 'Grand Lake', 'Broken Bow Lake', 'Oologah Lake',
    'Lower Mountain Fork River', 'Illinois River', 'Arkansas River',
  ],
  IL: [
    'Lake Michigan', 'Mississippi River', 'Illinois River',
    'Rend Lake', 'Lake Shelbyville', 'Carlyle Lake', 'Lake Springfield',
    'Clinton Lake', 'Kankakee River', 'Fox River',
  ],
  PA: [
    // Lake Erie + steelhead tribs
    'Lake Erie', 'Elk Creek', 'Walnut Creek',
    // Limestone trout streams
    "Penn's Creek", 'Spring Creek', 'Letort Spring Run',
    'Yellow Breeches Creek', 'Falling Spring Branch',
    // Freestone trout
    'Pine Creek', 'Loyalsock Creek', 'Kettle Creek', 'Fishing Creek',
    'Tulpehocken Creek',
    // Big-river smallmouth
    'Susquehanna River', 'Allegheny River', 'Delaware River',
    // Reservoirs
    'Lake Wallenpaupack', 'Raystown Lake', 'Pymatuning Lake',
  ],
  MT: [
    'Madison River', 'Bighorn River', 'Yellowstone River', 'Missouri River',
    'Beaverhead River', 'Big Hole River', 'Smith River', 'Blackfoot River',
    'Clark Fork River', 'Gallatin River',
    'Flathead Lake', 'Canyon Ferry Lake', 'Hauser Lake', 'Holter Lake',
    'Fort Peck Lake',
  ],
  ID: [
    'Snake River', 'South Fork Snake River', 'Henrys Fork', 'Teton River',
    'Big Lost River', 'Silver Creek',
    'Salmon River', 'Lochsa River', 'Selway River', 'St. Joe River',
    'Lake Pend Oreille', "Coeur d'Alene Lake", 'Priest Lake',
    'American Falls Reservoir', 'Palisades Reservoir',
  ],
  UT: [
    'Green River', 'Flaming Gorge Reservoir', 'Provo River', 'Weber River',
    'Logan River', 'Blacksmith Fork',
    'Strawberry Reservoir', 'Jordanelle Reservoir', 'Deer Creek Reservoir',
    'Bear Lake', 'Pineview Reservoir',
  ],
  CO: [
    // Gold Medal rivers
    'South Platte', 'Cheesman Canyon', 'Dream Stream', 'Arkansas River',
    'Frying Pan River', 'Roaring Fork River', 'Colorado River', 'Blue River',
    'Gunnison River', 'Yampa River', 'Rio Grande',
    // Reservoirs
    'Spinney Mountain Reservoir', 'Eleven Mile Reservoir', 'Antero Reservoir',
    'Blue Mesa Reservoir', 'Dillon Reservoir',
  ],
};
